export const EDITABLE_SITE_CONTENT_KEYS: Record<string, readonly string[]> = {
  hero: [
    'badge',
    'line1',
    'line2',
    'location',
    'static',
    'registrationCtaOpen',
    'registrationCtaClosed',
    'imageAlt',
  ],
  countdown: ['festival', 'days', 'hours', 'minutes', 'seconds'],
  marquee: ['item0', 'item1', 'item2', 'item3'],
  calendar: ['label', 'eyebrow', 'download', 'google', 'hint'],
  dasRennen: [
    'label',
    'headline1',
    'headline2',
    'stat0Value',
    'stat0Label',
    'stat2Value',
    'stat2Label',
    'stat3Value',
    'stat3Label',
    'body',
  ],
  festivalOverview: [
    'label',
    'headline1',
    'headline2',
    'body',
    'day0Label',
    'day0',
    'day1Label',
    'day1',
    'day2Label',
    'day2',
    'day3Label',
    'day3',
    'imageAlt',
  ],
  events: [
    'label',
    'headline',
    'item0Title',
    'item0Subtitle',
    'item1Title',
    'item1Subtitle',
    'item2Title',
    'item2Subtitle',
  ],
  news: ['label', 'headline', 'viewAll'],
  sponsors: ['label'],
  kajakfestival: [
    'scheduleHeading',
    'day1Day',
    'day1Date',
    'day1Desc',
    'day2Day',
    'day2Date',
    'day2Desc',
    'day3Day',
    'day3Date',
    'day3Desc',
    'day4Day',
    'day4Date',
    'day4Desc',
    'locationHeading',
    'locationText',
  ],
  kontakt: ['title', 'country', 'phone', 'orgHeading', 'socialHeading'],
  gallery: ['label', 'title', 'comingSoon', 'description'],
  results: ['label', 'title', 'comingSoon', 'description'],
  registration: [
    'label',
    'title',
    'intro',
    'formTitle',
    'formIntro',
    'raceLabel',
    'feeLabel',
    'firstNameLabel',
    'firstNamePlaceholder',
    'lastNameLabel',
    'lastNamePlaceholder',
    'emailLabel',
    'emailPlaceholder',
    'nationalityLabel',
    'nationalityPlaceholder',
    'tshirtLabel',
    'tshirtPlaceholder',
    'requiredNote',
    'termsPrefix',
    'termsLink',
    'termsSuffix',
    'awpPrefix',
    'awpLink',
    'awpSuffix',
    'ageConfirmation',
    'previewNotice',
    'closedTitle',
    'closedText',
    'submit',
    'submitting',
    'successTitle',
    'successRaceText',
    'backHome',
  ],
  terms: [
    'label',
    'title',
    'intro',
    'eligibilityHeading',
    'eligibilityText',
    'rulesHeading',
    'rulesText',
    'paymentHeading',
    'paymentText',
    'dataHeading',
    'dataText',
    'reviewNote',
  ],
  programm: ['label', 'title', 'intro', 'mapHeading', 'mapComingSoon'],
  nav: [
    'switchTo',
    'race',
    'boaterX',
    'festival',
    'program',
    'news',
    'registration',
    'contact',
    'menuLabel',
  ],
  footer: ['followUs', 'tagline', 'impressum', 'kontakt', 'datenschutz', 'terms', 'copyright'],
  impressum: [
    'label',
    'title',
    'country',
    'phone',
    'liabilityHeading',
    'liabilityText',
  ],
  datenschutz: [
    'label',
    'title',
    'phone',
    'intro',
    's1Heading',
    's1Text',
    's2Heading',
    's2Text',
    's3Heading',
    's3Text',
    's4Heading',
    's4Text',
    's5Heading',
    's5Text',
    's6Heading',
    's6Text',
    's7Heading',
    's7Text',
    's8Heading',
    's8Text',
  ],
};
